host: 127.0.0.1:8080
info:
  contact:
    email: me@test.me
    name: www.test.com
    url: https://www.test.com
  description: 声明（可不写）
  license:
    name: Apache 2.0 (必填)
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.test.com
  title: 标题
  version: 1.0 (版本)
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: 向你说Hello
      parameters:
      - description: 人名
        in: query
        name: who
        required: true
        type: string
      responses:
        "200":
          description: '{"msg": "hello Razeen"}'
          schema:
            type: string
        "400":
          description: '{"msg": "who are you"}'
          schema:
            type: string
      tags:
      - 测试
swagger: "2.0"
